on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io/homebots/xtensa-gcc
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Self-test
        run: docker run --rm -v$PWD/tests/hello-world:/home/project -v$PWD:/home/homebots-sdk ghcr.io/homebots/xtensa-gcc make
